### ISSUE TITLE
FactoryContext.test not detected in SPM tests

### ISSUE THREAD

**Issue by mbrandonw** [hmlongco/Factory#94]
If you run Factory's test suite through SPM using `swift test` (rather than through Xcode) you will find that 2 tests fail:

```
$ swift test

FactoryContextTests.swift:55: error: XCTAssertEqual failed: ("REGISTERED") is not equal to ("TEST")
FactoryContextTests.swift:57: error: XCTAssertEqual failed: ("DEBUG") is not equal to ("TEST")
```

This is because [`isTesting`](https://github.com/hmlongco/Factory/blob/3b47ec87350436667e740e85f01ab1280707d8ec/Sources/Factory/Factory/Contexts.swift#L64) checks for an environment variable that Xcode provides, but `swift` from the command line does not.

**Comment by hmlongco** [comment]
Think this is fixed in current 2.1.3 pre-release on main.

**Comment by iDylanK** [comment]
It seems like this still does not work.
When running my tests using 'swift test' the containers are not registered for testing.
However, when running ;xcodebuild test' they are registered.
